name: Edit Story Metadata 

env:
  upstream: BrownCLPS/LingView
  upstream_branch: master
  base_branch: master
  pr_branch: master-upgrade

on: workflow_dispatch 

jobs:
  check-actor:
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check-repo:
    runs-on: ubuntu-latest
    outputs:
      is-core: ${{ github.repository == env.upstream }}
    steps:
      - name: Log result
        run: 'echo "Checking if repository is the upstream repository... $answer"'
        env:
          answer: ${{ github.repository == env.upstream }}

  edit-data:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Debug Session
        uses: csexton/debugger-action@master

      

  upgrade:
    needs: [check-actor, check-repo, edit-data]
    if: needs.check-repo.outputs.is-core == 'false'
    runs-on: ubuntu-latest
    env:
      actor: ${{ github.actor }}
      actoremail: ${{ github.actor }}@users.noreply.github.com
    steps:
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.base_branch }}
          fetch-depth: 0 # fetch the whole history (necessary for merge)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Upgrade LingView core version after editing story metadata
          committer: GitHub <noreply@github.com>
          title: 'Edit story metadata'
          body: |
            Pull request to upgrade story metadata. 
            
            > I automatically ignored any changes made to the `data/` folder, so your FLEx and ELAN files will not be changed. :)
            > 
            > When you review this, please make sure I didn't accidentally undo any of your LingView customizations (e.g. if your `index.html` or `jsx/App/AboutPage.jsx` is different from the version at `${{ env.upstream }}`)!
            > 
            > ${{ env.conflicts_message }} 
            > 
            > ${{ env.workflows_message }}

            _Auto-generated by [create-pull-request][1]_

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automated pr
          branch: ${{ env.pr_branch }}
          